[project]
name = "etherfi-vault-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "sqlalchemy>=2.0.44",
    "telegram>=0.0.1",
    "web3>=7.14.0",
]
